### ISSUE TITLE
Some bugs to fix

### ISSUE THREAD

**Issue by PMassicotte** [jalvesaq/tmp-R-Nvim#34] opened 2024-02-16 12:36 UTC
Just listing issues I am finding so we can fix them :)

- [x] `rh` (for help) is not working for a namespaced function. For example `pack::fun()`
- [x] `rp` for printing an object is not always working (see attached GIF).  Might use `vim.fn.expand("<cword>")`
![Peek 2024-02-16 07-34](https://github.com/jalvesaq/tmp-R-Nvim/assets/4519221/aa58011e-20b8-4a52-a39c-dc73ecf49345)

I think it is coming from these lines:

https://github.com/jalvesaq/tmp-R-Nvim/blob/7fd9fffcc870652bdad1e3e7dd0fee66e879a40a/lua/r/run.lua#L601-L605

**Comment by PMassicotte** [comment] 2024-02-16 13:01
An option to send the current object to the terminal:

```lua
    if rcmd == "print" then
        send.cmd(vim.fn.expand("<cword>"))
        return
    end
```

**Comment by jalvesaq** [comment] 2024-02-16 13:03
> An option to send the current object to the terminal:

The problem is that `vim.fn.expand("<cword>")` will not catch strings such as `listname$element`.

**Comment by jalvesaq** [comment] 2024-02-16 13:09
But we could try to change the value of `vim.o.iskeywords` temporarily. It will be much simpler than the complicated algorithm that I have written.

**Comment by jalvesaq** [comment] 2024-02-16 13:12
`nvimcom` and `rnvimserver` now send Lua tables to R.nvim. You have to update `cmp-nvim-r`.
There are some bugs when completing functions from `.GlobalEnv`, but I will fix them later.

**Comment by jalvesaq** [comment] 2024-02-16 13:28
The problem while running `<LocalLeader>rp` is the function `get_first_obj()`. It has to be rewritten from scratch.

**Comment by PMassicotte** [comment] 2024-02-16 13:43
Has something about terminal color changed this recently? Looks like a new config is coloring my terminal

**Comment by jalvesaq** [comment] 2024-02-16 13:48
Yes, `hl_term` is being defined as `true`, but `nvimcom/R/nvimcom.R` should detect `radian`:

```r
    if (length(find.package("colorout", quiet = TRUE, verbose = FALSE)) > 0 || Sys.getenv("RADIAN_VERSION") != "")
        hascolor <- TRUE
```

**Comment by PMassicotte** [comment] 2024-02-16 13:49
It was opening radian, but my console was all green-ish.

**Comment by jalvesaq** [comment] 2024-02-16 13:53
I did a minor improvement in `get_first_obj`. With the following code:

```r
x <- rnorm(100)
y <- rnorm(100)
m <- lm(y ~ x)
summary(x)
summary(m)
```

If you press `<LocalLeader>rp` over `summary`, you should get different results for each `summary()`

**Comment by jalvesaq** [comment] 2024-02-16 14:13
I moved the check for radian to the config. It's working there.

**Comment by PMassicotte** [comment] 2024-02-16 14:54
> I did a minor improvement in `get_first_obj`. With the following code:
> 
> ```r
> x <- rnorm(100)
> y <- rnorm(100)
> m <- lm(y ~ x)
> summary(x)
> summary(m)
> ```
> 
> If you press `<LocalLeader>rp` over `summary`, you should get different results for each `summary()`

Is it works if my cursor is either on `x` or `m` !

**Comment by jalvesaq** [comment] 2024-02-17 20:56
I rewrote `get_first_obj()` and now it is as good and as bad as Nvim-R's version. I don't want to improve it any further because perhaps it will be possible (and better) to rewrite it using tree-sitter in the future. To quickly test the function, I have put this in my `init.lua`:

```lua
vim.keymap.set("n", "T", function ()
    vim.api.nvim_echo({
        {"{"},
        {require("r.run").get_keyword(), "Function"},
        {"} {"},
        {require("r.cursor").get_first_obj(), "Type"},
        {"}"}}, false, {})
end, { expr = true})
```

**Comment by jalvesaq** [comment] 2024-02-17 21:00
>  `rh` (for help) is not working for a namespaced function. For example `pack::fun()`

I can't replicate this. It works for me, for example doing `<LocalLeader>rh` over the word `vi`:

```r
vi
nvimcom::vi
utils::vi
```

**Comment by PMassicotte** [comment] 2024-02-17 22:14
Placing my cursor on `library` and hitting `<LocalLeader>rh` does nothing. With the older nrim-r, it opens the help file for the `library()` function.

![image](https://github.com/jalvesaq/tmp-R-Nvim/assets/4519221/00571f3a-9fbc-4564-89b9-ac91c5c09eaa)

Now, placing my cursor on `vi` indeed brings me a _topic menu_. Then, If I select either 1 for nvimcom or 2 for utils, nothing happens.

![image](https://github.com/jalvesaq/tmp-R-Nvim/assets/4519221/8be2f431-48ad-4ae9-8719-1cd4a82c8b2e)

**Comment by jalvesaq** [comment] 2024-02-17 23:04
Maybe you have set `options("pager")` in your `~/.Rprofile`... I couldn't think of another explanation.

**Comment by jalvesaq** [comment] 2024-02-18 00:58
Also: `\rh` only works if R is running, but, if not, R.nvim displays a warning message.

**Comment by PMassicotte** [comment] 2024-02-18 08:36
No option about pager in my rprofile.

Even typing `?lm` in the console does nothing.


![Peek 2024-02-18 03-35](https://github.com/jalvesaq/tmp-R-Nvim/assets/4519221/14a8ff28-495f-461f-88ea-ccc1af5e2968)

**Comment by PMassicotte** [comment] 2024-02-18 08:38
The only pager option I have is this config:

```lua
opts = {
   ...
   nvimpager = "horizontal",
   ...
  }
```

**Comment by jalvesaq** [comment] 2024-02-18 08:55
With this option, I receive a warning message:

Invalid `nvimpager` value: "horizontal". Valid values are: "tab", "split", "float", and "no".

And nothing more happens. Hence, we have to investigate why you are not receiving this warning.

**Comment by PMassicotte** [comment] 2024-02-18 11:26
You are right, it works as before when using 'split'. I probably missed the change of the parameter (i.e. using an old value that was working with nvim-r).

**Comment by PMassicotte** [comment] 2024-02-18 11:27
I think we can close this now.

**Comment by PMassicotte** [comment] 2024-02-18 11:30
What is supposed to be the file type of rdoc?

For me, `:set filetype?` returns nothing

![image](https://github.com/jalvesaq/tmp-R-Nvim/assets/4519221/404669f7-9868-4433-8d33-a8977e40fcd1)

Hence, sending example code in the terminal is not working because not recognized as r code.

**Comment by jalvesaq** [comment] 2024-02-18 11:38
The warning should be wrapped by `vim.schedule()`. This is fixed now.

**Comment by jalvesaq** [comment] 2024-02-18 11:39
The filetype `rdoc` no longer exists; only the syntax is being used.

**Comment by jalvesaq** [comment] 2024-02-18 11:41
It was a filetype that I created to display R documentation. Its functions are now in `lua/r/rdoc.lua`.

**Comment by PMassicotte** [comment] 2024-02-18 11:41
> The filetype `rdoc` no longer exists; only the syntax is being used.

Do you have a good strategy to send example code to the console?  I found it was a nice thing to do while browsing code example and have the ability to send it to the console.

**Comment by jalvesaq** [comment] 2024-02-18 11:43
Yes, please, do `git pull` to get the warnings. I didn't see the warn bug because I had this in my lazy.nvim config:

```lua
    {
        'rcarriga/nvim-notify',
        config = function ()
            -- Overriding vim.notify with fancy notify
            local notify = require("notify")
            vim.notify = notify
            notify.setup()
            vim.keymap.set('',  '<Esc>', "<ESC>:noh<CR>:lua require('notify').dismiss()<CR>", {silent = true})
        end
    },
```

**Comment by jalvesaq** [comment] 2024-02-18 11:46
`\re` to get the "Examples" section in an R buffer.

**Comment by PMassicotte** [comment] 2024-02-18 11:51
Another thing I am just facing is that sending above code does not always work. In this example, moving the cursor 2 lines below give me an error *cannot open the connection*

![Peek 2024-02-18 06-49](https://github.com/jalvesaq/tmp-R-Nvim/assets/4519221/75c35f9b-629d-4292-b8ca-f4254b0f8c61)

**Comment by jalvesaq** [comment] 2024-02-18 11:53
But you can also send lines from the Example section to R. The rdoc is modifiable to allow you to edit the examples. There was a bug that I fixed just now.

**Comment by PMassicotte** [comment] 2024-02-18 11:55
> But you can also send lines from the Example section to R. The rdoc is modifiable to allow you to edit the examples. There was a bug that I fixed just now.

You are on fire :)

**Comment by jalvesaq** [comment] 2024-02-18 12:39
> Another thing I am just facing is that sending above code does not always work. In this example, moving the cursor 2 lines below give me an error _cannot open the connection_. Moving back the cursor up, make it works again.

Two lines above you were below the threshold of 20 lines to source lines and the lines were sent directly. I introduced the bug yesterday when fixing user config variables not being recognized. It should be fixed now.

**Comment by PMassicotte** [comment] 2024-02-18 12:47
All perfect now!

**Closed** 2024-02-20 11:30 UTC
